/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    CloudflareAuth: {
      type: "sst.cloudflare.Worker"
      url: string
    }
    CloudflareAuthKV: {
      type: "sst.cloudflare.Kv"
    }
  }
}
