/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
import "sst"
declare module "sst" {
  export interface Resource {
    "LambdaApi": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "LambdaAuth": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "LambdaAuthTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
// cloudflare 
import * as cloudflare from "@cloudflare/workers-types";
declare module "sst" {
  export interface Resource {
    "CloudflareApi": cloudflare.Service
    "CloudflareAuth": cloudflare.Service
    "CloudflareAuthKV": cloudflare.KVNamespace
  }
}
