/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    MyAuth: {
      type: "sst.aws.Auth"
      url: string
    }
    MyWeb: {
      type: "sst.aws.Nextjs"
      url: string
    }
  }
}
